[package]
name = "uniffi-bindgen-swift"
version = "0.1.0"
publish = false
edition.workspace = true

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[[bin]]
name = "uniffi-bindgen-swift"
path = "src/main.rs"
