name: Android Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["iOS Release"]
    types:
      - completed

jobs:
  release:
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk --force

      - name: Touch local.properties (required for build)
        run: touch local.properties
        working-directory: android

      - name: 📤 Publish Package
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository
        working-directory: android
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
