name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag, or SHA to check out"
        required: true
        type: string
      github-release:
        description: "Publish GitHub release?"
        required: false
        type: boolean
        default: false

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Neon Environment
        uses: ./.github/actions/setup-neon
        with:
          use-rust: false

      - name: Look Up Matrix Data
        id: matrixData
        shell: bash
        run: echo "json=$(npx neon show ci github | jq -rc)" | tee -a $GITHUB_OUTPUT
        working-directory: node

      - name: Compute Matrix
        id: matrix
        uses: actions/github-script@v7
        with:
          script: |
            const platforms = ${{ steps.matrixData.outputs.json }};
            const macOS = platforms.macOS.map(platform => {
              return { os: "macos-latest", platform, script: "build" };
            });
            const windows = platforms.Windows.map(platform => {
              return { os: "windows-latest", platform, script: "build" };
            });
            const linux = platforms.Linux.map(platform => {
              return { os: "ubuntu-latest", platform, script: "cross" };
            });
            return [...macOS, ...windows, ...linux];

  binaries:
    name: Binaries
    needs: [matrix]
    strategy:
      matrix:
        cfg: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.cfg.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Neon Environment
        id: neon
        uses: ./.github/actions/setup-neon
        with:
          use-cross: ${{ matrix.cfg.script == 'cross' }}
          platform: ${{ matrix.cfg.platform }}

      - name: Build
        shell: bash
        env:
          CARGO_BUILD_TARGET: ${{ steps.neon.outputs.target }}
          NEON_BUILD_PLATFORM: ${{ matrix.cfg.platform }}
        run: pnpm run ${{ matrix.cfg.script }}
        working-directory: node

      - name: Pack
        id: pack
        shell: bash
        run: |
          mkdir -p dist
          echo filename=$(basename $(npm pack ./platforms/${{ matrix.cfg.platform }} --silent --pack-destination=./dist --json | jq -r '.[0].filename')) | tee -a $GITHUB_OUTPUT
        working-directory: node

      - name: Get latest release tag
        id: get-tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "Latest tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        shell: bash

      - name: Release
        if: ${{ inputs.github-release }}
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
        with:
          files: ./node/dist/${{ steps.pack.outputs.filename }}
          tag_name: ${{ steps.get-tag.outputs.tag }}

  main:
    name: Main
    needs: [matrix]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Neon Environment
        uses: ./.github/actions/setup-neon
        with:
          use-rust: false

      - name: Pack
        id: pack
        shell: bash
        run: |
          mkdir -p dist
          echo "filename=$(npm pack --silent --pack-destination=./dist)" | tee -a $GITHUB_OUTPUT
        working-directory: node

      - name: Get latest release tag
        id: get-tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "Latest tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        shell: bash

      - name: Release
        if: ${{ inputs.github-release }}
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2.0.4
        with:
          files: ./node/dist/${{ steps.pack.outputs.filename }}
          tag_name: ${{ steps.get-tag.outputs.tag }}
